<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            // Electronics (category_id = 1)
            [
                'id' => 1,
                'name' => 'computer 148',
                'description' => 'At suscipit odit accusamus eius. Id ut expedita quisquam illo. Adipisci voluptas eveniet incidunt vel excepturi vero non.',
                'price' => 752.47,
                'stock_quantity' => 160,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 3,
                'name' => 'earphone 875',
                'description' => 'Aliquid quas consequatur rerum fuga magnam. Atque qui eos distinctio. Aliquam tempora velit iste blanditiis blanditiis. Aut quae consectetur quia vel.',
                'price' => 192.49,
                'stock_quantity' => 17,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 6,
                'name' => 'earphone 018',
                'description' => 'Voluptatem perferendis incidunt libero et. Esse ea molestiae repellendus est. Eveniet sequi officiis esse beatae.',
                'price' => 645.76,
                'stock_quantity' => 290,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 9,
                'name' => 'earphone 645',
                'description' => 'Illum expedita perferendis officia illum facilis quia. Natus quas necessitatibus deserunt porro necessitatibus. Soluta eveniet commodi accusamus aperiam dicta.',
                'price' => 303.48,
                'stock_quantity' => 55,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 11,
                'name' => 'computer 560',
                'description' => 'Asperiores tempore porro aliquid amet rerum quo harum ut. Rem optio qui velit nobis doloremque reiciendis. Ratione qui architecto culpa veniam quia delectus. Omnis laudantium aut expedita inventore aut.',
                'price' => 107.63,
                'stock_quantity' => 327,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 12,
                'name' => 'computer 261',
                'description' => 'Distinctio vero vel placeat qui autem. Rerum temporibus dolores sapiente error et. Praesentium quo esse a nihil omnis rerum. Fuga sint amet repudiandae porro autem qui dolorem dolores.',
                'price' => 657.22,
                'stock_quantity' => 487,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 13,
                'name' => 'computer 516',
                'description' => 'Corrupti maiores non iusto autem et. Sit non sit sit tenetur. Excepturi accusamus dolor hic aliquid ad. Quasi adipisci expedita magnam non et.',
                'price' => 494.75,
                'stock_quantity' => 339,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 15,
                'name' => 'earphone 461',
                'description' => 'Aut id et qui nisi fugit aut. Quas libero a sed molestias.',
                'price' => 830.71,
                'stock_quantity' => 359,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 19,
                'name' => 'earphone 753',
                'description' => 'Eaque ipsa excepturi qui cumque. Debitis ut molestiae tempore facilis pariatur pariatur. Debitis labore et aut corporis eum.',
                'price' => 541.62,
                'stock_quantity' => 338,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],

            // Clothes (category_id = 2)
            [
                'id' => 2,
                'name' => 'shirt 127',
                'description' => 'At est sit impedit. Minus ipsam blanditiis exercitationem molestias quo est. Accusamus veritatis autem aut culpa animi. Ut reiciendis doloremque quos dicta repellat. Sunt et ex voluptatem atque.',
                'price' => 558.61,
                'stock_quantity' => 172,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 4,
                'name' => 'shirt 037',
                'description' => 'Est porro dolorum quam fugit quaerat in. Deserunt quia corporis harum.',
                'price' => 486.19,
                'stock_quantity' => 106,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 5,
                'name' => 'computer 760',
                'description' => 'Repellat error et sunt placeat voluptatum. Asperiores eos qui assumenda consequatur corporis dolorem. Qui maiores quibusdam eaque in blanditiis molestiae consectetur aut. Voluptas ipsum non eos est facilis repellat saepe similique.',
                'price' => 202.12,
                'stock_quantity' => 160,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 7,
                'name' => 'shirt 630',
                'description' => 'Aliquam possimus id laborum ut. Et laborum corporis odio. Ad alias dicta similique quis qui. Dolorem et sed cumque eos atque reprehenderit sapiente est.',
                'price' => 918.59,
                'stock_quantity' => 434,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 8,
                'name' => 'shirt 255',
                'description' => 'Inventore fuga perferendis itaque et. Voluptate earum sit et voluptatem quia facilis non ab. Corrupti aut expedita voluptate eos.',
                'price' => 18.21,
                'stock_quantity' => 128,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 10,
                'name' => 'shirt 769',
                'description' => 'Et reprehenderit assumenda nobis. Cum aut corporis natus. Reprehenderit iusto id beatae.',
                'price' => 76.27,
                'stock_quantity' => 457,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 14,
                'name' => 'shirt 945',
                'description' => 'Possimus quae deserunt qui sequi et voluptas ut molestias. Eius doloremque est dolores et enim. Animi quia omnis dolore error.',
                'price' => 333.50,
                'stock_quantity' => 9,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 16,
                'name' => 'shirt 500',
                'description' => 'Amet sed repudiandae quo laudantium. Veniam blanditiis itaque ut et omnis. Modi placeat consectetur distinctio minima qui nesciunt. Vel qui voluptatem consequatur laboriosam sit placeat.',
                'price' => 316.38,
                'stock_quantity' => 205,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 17,
                'name' => 'computer 450',
                'description' => 'Ex unde voluptatem quo placeat quia est veritatis consequatur. Consequuntur perspiciatis alias dignissimos maiores repellendus repudiandae nemo. Sed quis occaecati eaque maiores. Suscipit temporibus minima incidunt quidem blanditiis sed.',
                'price' => 217.09,
                'stock_quantity' => 306,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 18,
                'name' => 'shirt 790',
                'description' => 'Dolorem eveniet unde omnis cumque et. Error dolor cupiditate perspiciatis consequatur accusamus iste vitae optio. Perspiciatis facilis et sapiente veniam. Et adipisci ipsum illo perferendis aut possimus.',
                'price' => 290.24,
                'stock_quantity' => 380,
                'category_id' => 2,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
            [
                'id' => 20,
                'name' => 'earphone 963',
                'description' => 'Qui consequatur ut aspernatur molestiae consequuntur. Officia aut qui voluptatem et enim. Qui perferendis velit doloremque et. Amet iure quia deleniti praesentium ad ducimus non.',
                'price' => 397.21,
                'stock_quantity' => 454,
                'category_id' => 1,
                'created_at' => '2025-08-13 03:26:21',
                'updated_at' => '2025-08-13 03:26:21',
            ],
        ]);
    }
}
